package Account.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class AccountLifeCycleStatus_Constraints extends BaseConstraintsDescriptor {
  public AccountLifeCycleStatus_Constraints() {
    super(CONCEPTS.AccountLifeCycleStatus$gF);
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept AccountLifeCycleStatus$gF = MetaAdapterFactory.getConcept(0x1b5f79a9a6464e86L, 0xb0dcaa13ea6dc8d2L, 0x1e60c5d7fc1f2e0eL, "Account.structure.AccountLifeCycleStatus");
  }
}
