package Account.sandbox;

/*Generated by MPS */


public class AccountManagementRulesImpl {
  public static void main(String[] args) {
    new AccountManagementRulesImpl();
  }
  public AccountManagementRulesImpl() {
  }

}
